### ISSUE TITLE
Question on use case within javascript code

### ISSUE THREAD

**Issue by hsdk123** [jldupont/prolog.js#1]
Hi, I was noticing that there aren't any clear examples of how prolog files can be parsed in javascript files. Such that for example, the result of a query (true/false, or perhaps a list) can be used as input that can be fed back into other javascript functions.

Would it be possible to provide an example of how this might be done?

**Comment by jldupont** [comment]
Hi - you can look under /tests  and more specifically test_q_interpreter2.js.
